name: First action

on:
  pull_request:
    types: [opened, reopened, edited]

jobs:
  get-info:
    name: Get PR Date
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Add PR created date to comment
        uses: andrewmusgrave/automatic-pull-request-review@0.0.2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          event: APPROVE
          body: 'Дата создания 1: ${{ github.event.pull_request.created_at }}'

    