name: Check PR date and time creation

on:
  pull_request:
    branches: [master, main]
    types: [opened, synchronize, reopened, edited]

jobs:
  get-date-and-time:
    runs-on: ubuntu-latest
    steps:
      - name: Get PR date and time creation
        run: |
          python3 <<END
          import time
          
          data = '${{github.event.pull_request.created_at}}'
          date = time.strptime(data, '%Y-%m-%dT%H:%M:%SZ')
          creation_date = time.strftime('%Y-%m-%d', date)
          creation_time = time.strftime('%H:%M:%S', date)
          print(f'Дата создания: {creation_date}')
          print(f'Время создания: {creation_time}')

          END
            