name: First action

on:
  pull_request:
    types: [opened, synchronize, reopened, edited]

jobs:
  get-date:
    name: Дата и время создания PR
    runs-on: ubuntu-latest
    steps:
      - name: Проверка даты и времени создания PR
        run: |
          python3 <<END
          import time
          
          data = '${{github.event.pull_request.created_at}}'
          date = time.strptime(data, '%Y-%m-%dT%H:%M:%SZ')
          creation_date = time.strftime('%Y-%m-%d', date)
          creation_time = time.strftime('%H:%M:%S', date)
          print(f'Дата создания: {creation_date}')
          print(f'Время создания: {creation_time}')

          END
            